FROM gradle:8.1.1-jdk11-alpine AS build
COPY . .
RUN ./gradlew bootJat --no-daemon

FROM openjdk:11-jdk-slim
COPY --from=build /build/libs/rest-0.0.1-SNAPSHOT.jar rest.jar
EXPOSE 8080
ENTRYPOINT [ "java","-jar","rest.jar"]

